version: "3"
services:
  backend:
    image: backend:latest
    ports:
      - "8080:8080"
  # backend:
  #   image: nginx:latest
  #   ports:
  #     - 80:80
  frontend:
    image: frontend:latest
    ports:
      - "5173:5173"
    depends_on:
      - backend
